# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190416_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821')], default='pxjg', max_length=100, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
