# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190405_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='course',
        ),
    ]
