# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_category'),
        ('operation', '0003_remove_userfavorite_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b'),
            preserve_default=False,
        ),
    ]
