# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
