# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190516_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u540e\u7aef\u5f00\u53d1', max_length=40, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
