# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u89c6\u9891\u540d'),
            preserve_default=False,
        ),
    ]
