# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='mins',
        ),
        migrations.AddField(
            model_name='video',
            name='mins',
            field=models.CharField(default='10:00', max_length=10, verbose_name='\u65f6\u957f'),
        ),
    ]
