# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190511_1307'),
        ('courses', '0013_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotice',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u6559\u5e08'),
            preserve_default=False,
        ),
    ]
